import Head from "next/head";
import { useMoralis } from "react-moralis";
import Login from "../components/Login";

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();

  if (!isAuthenticated) return <Login />;
  return (
    <div>
      <Head>
        <title>Metaverse Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <h1>This is the app</h1>
      <button
        onClick={logout}
        className="bg-yellow-500 p-5 font-bold animate-pulse rounded-lg"
      >
        Logout
      </button>
    </div>
  );
}
