import Head from "next/head";
import Login from "../components/Login";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Metaverse Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <Login />
    </div>
  );
}
