import Head from "next/head";
import { useMoralis } from "react-moralis";
import Header from "../components/Header";
import Login from "../components/Login";
import Messages from "../components/Messages";

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();

  if (!isAuthenticated) return <Login />;
  return (
    <div className="h-screen overflow-y-scroll bg-gradient-to-b from-black to-fuchsia-900 overflow-hidden">
      <Head>
        <title>Metaverse Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>

      <div className="max-w-2xl mx-auto">
        <Header />

        <Messages />
      </div>
      <button
        onClick={logout}
        className="bg-yellow-500 p-3 font-bold animate-pulse rounded-lg"
      >
        Logout
      </button>
    </div>
  );
}
